* [[https://andreypudov.com][Andrey Pudov]]

Driven professional with broad technical skill set. Thrives in environments that constantly embrace new technologies. Interested in challenging and varied position that will enable me to capitalize on sound technical and project management expertise, with opportunities for personal and professional growth.

** Experience

*** *Combination AB*
  - *Sr. Software Development Engineer* / 2021 - present

*** *EPAM Systems*
  - *Sr. Software Development Engineer** / 2020 - 2021

    Developed an innovative platform for data-driven facility management decision-making for United States Golf Association, employing scalable microservice architecture on Microsoft Azure cloud infrastructure. Designed and maintained RESTful APIs services build on top of ASP.NET Core, Entity Core, Microsoft. SQL Server, Kafka, Autofac, and AutoMapper. Created extensive unit, and integration tests in a test-driven development environment.

    Led and mentored a team of interns working on the random coffee website that helps build great relationships with the company members. Involved in gathering and in understanding the business requirements of the project. Helped interns to create short-term and long-term goals and supported them along the way. Offered guidance to deal with challenging problems and meet deadlines.

*** *Intel Corporation*
  - *Senior Software Engineer Technical Lead* / 2018 - 2020

    Took the role of team leader for the new team in Nizhny Novgorod. Actively participated in hiring and team building process by mentoring almost all hired employees and ensuring their quick and efficient integration. In addition, drove engagement with business-critical stakeholders and organization of product building and distribution processes.

    Led building of new project infrastructure and helped to set up new continuous integration infrastructure in a very short time. As the result, drastically reduced project build time, significantly improved code management and review process using best-known development and testing methods.

    Implemented several business-critical features. Led the implementation of critical security vulnerability fixes that was done in collaboration with other teams in a quick and efficient manner (w/o impact for release). In addition, coordinated the work with customers starting from initial feedback with many reported blocker issues and finishing with fixed product delivery.

  - *Sr. Software Development Engineer* / 2013 - 2018

    Software engineer responsible for the design, development, and maintenance of the Intel Registration Center entitlement and download website for Intel software products, focusing on user interface and system APIs.

    Designed and developed the new website architecture for Intel Registration Center using modern user interface. A primary contributor to migration of ASP.NET web pages to MVC technology. Using MVC pages improves website performance, provides better user experience, and is easier to maintain.

    Implemented a modern role-based rights model. User account access to web pages can be managed dynamically by assigning them to required roles.

    Implemented infrastructure and processes for automated project deployment. This includes source code compilation, configuration file transformations, publishing to integration servers in the development and pre-production environments. This allows for automated, error-free, reproducible code migrations.

  - *Software Development Engineer* / 2011 - 2013

    Main software developer for common licensing and installation technologies for Intel software products on Linux. Added the crucial Graphical User Interface functionality. Developed a wizard for the installation client, a tool used to create product installs. Showed quality commitment in developing the Automated Unit Test System to improve the capability to find bugs earlier in the development process.

    Implemented the code signing interface in the installation client. Also developed and integrated the Smart Cache and Shell Executor features into the installation client for Linux to significantly decrease initialization and common execution time.

** Recommendations

*** *Viktorya Gvozdeva*

  Andrey was a technical leader in my team for approximate 2 years. He is a professional and very experienced engineer! Andrey really helped me on my way from intern to engineer. He gave me an understanding how to resolve technical challenges in the best way. I extend my programming and soft skills very fast with his help and advices. Andrey's background and strong problem resolving skills helped to the team to resolve technical challenges. Working with Andrey was a great opportunity for me!

*** *Tanya Zaslavsky*

  Andrey and I worked in the same group for a few years in Intel. This group was responsible for the system which registered and distributed Intel software.Andrey showed himself as a UI wizard and a quick learner. He is a person with high levels of professionalism, integrity and above the expert level knowledge of DevOps tools, Bootstrap, AngularJS frameworks. This made Andrey a primary expert in those areas for our team. With people like Andrey on the team lead as well as a project manager you will not have any problems completing any task or project in schedule time with high quality.

*** *Doug Helbling*

  I worked with Andrey as part of a global team for a number of years. It was a joy to work with such a talented engineer and skilled communicator. He brings his best to every effort.

*** *Paul Frumkin*

  I worked with Andrey for many years, and I was his manager for three years. He is a very strong software engineer, particularly in User Interface but he also can develop middleware and backend database. He keeps up with technology which allows him to apply the latest techniques for automation problem solving. He is a quick learner and documents his implementations for other team members to learn and follow. He is team oriented and communicates well.
