import Album from '../core/photographyAlbum';
import Photograph from '../core/photograph';
import Text from '../core/text';

const BarcelonaAirport = new Album(
  new Text('BarcelonaAirport.Title', 'LEBL Barcelona El Prat International Airport'),
  new Date('2023-05-17'),
  new Photograph('/photographs/2023-05-17/2023-05-17_011.webp'),
  [
   new Photograph('/photographs/2023-05-17/2023-05-17_001.webp', true, new Text('Montserrat.', 'Josep Tarradellas Barcelona–El Prat Airport is the largest and busiest airport in Catalonia, and the sixth busiest in Europe. In 2019, Barcelona Airport handled a record 52,686,314 passengers, up 5.0% from 2018. It is a hub for Level and Vueling, and a focus city for Air Europa, Iberia, EasyJet and Ryanair.')),
   new Photograph('/photographs/2023-05-17/2023-05-17_002.webp', true, new Text('Montserrat.', 'Ryanair DAC is an Irish ultra low-cost carrier founded in 1984. It is headquartered in Swords, Dublin, Ireland, and has its primary operational bases at Dublin and London Stansted airports. It forms the largest part of the Ryanair Holdings family of airlines and has Ryanair UK, Buzz, Lauda Europe, and Malta Air as sister airlines. It is Ireland\'s biggest airline and in 2016 became Europe\'s largest budget airline by scheduled passengers flown, carrying more international passengers than any other airline.')),
   new Photograph('/photographs/2023-05-17/2023-05-17_003.webp', true, new Text('Montserrat.', 'TAP Air Portugal is the flag carrier of Portugal, headquartered at Lisbon Airport which also serves as its hub. The airline was established on 14 March 1945 and began commercial services on 19 September 1946. TAP – Transportes Aéreos Portugueses – has been a member of the Star Alliance since 2005 and operates on average 2,500 flights a week to 90 destinations in 34 countries worldwide. The company has a fleet of 100 aircraft, all of which are manufactured by Airbus with the exception of 22 aircraft manufactured by Embraer and ATR, operating on behalf of the regional airline TAP Express.')),
   new Photograph('/photographs/2023-05-17/2023-05-17_004.webp', true, new Text('Montserrat.', 'Vueling is a Spanish low-cost airline based at Viladecans in Greater Barcelona with hubs at Barcelona–El Prat Airport (main), Paris-Orly Airport in Paris, France and Leonardo da Vinci–Fiumicino Airport in Rome, Italy (secondary). It is the largest airline in Spain, measured by fleet size and number of destinations. As of 2021, Vueling serves 122 destinations in Africa, Asia, Europe and the Middle East, and carried more than 34 million passengers in 2019. Since 2013, it has been an operating company of International Airlines Group, the parent company of British Airways and Iberia.')),
   new Photograph('/photographs/2023-05-17/2023-05-17_005.webp'),
   new Photograph('/photographs/2023-05-17/2023-05-17_006.webp', true),
   new Photograph('/photographs/2023-05-17/2023-05-17_007.webp', true),
   new Photograph('/photographs/2023-05-17/2023-05-17_008.webp', true),
   new Photograph('/photographs/2023-05-17/2023-05-17_009.webp'),
   new Photograph('/photographs/2023-05-17/2023-05-17_010.webp', true, new Text('Montserrat.', 'Scandinavian Airlines, more commonly known and styled as SAS, is the flag carrier of Denmark, Norway, and Sweden. Part of the SAS Group and headquartered at the SAS Frösundavik Office Building in Solna, Sweden, the airline operates 180 aircraft to 90 destinations. The airline\'s main hub is at Copenhagen-Kastrup Airport, with connections to 109 destinations around the world. Stockholm Arlanda Airport is the second largest hub, with Oslo Airport, Gardermoen being the third major hub of SAS. Minor hubs also exist at Bergen Airport, Flesland, Göteborg Landvetter Airport, Stavanger Airport, Sola, and Trondheim Airport, Værnes. SAS Cargo is an independent, wholly owned subsidiary of Scandinavian Airlines and its main office is at Copenhagen Airport.')),
   new Photograph('/photographs/2023-05-17/2023-05-17_011.webp'),
   new Photograph('/photographs/2023-05-17/2023-05-17_012.webp', true, new Text('Montserrat.', 'Barcelona\'s first airfield, located at El Remolar, began operations in 1916. However, it did not have good expansion prospects, so a new airport at El Prat opened in 1918. The first plane was a Latécoère Salmson 300 which arrived from Toulouse with final destination Casablanca. The airport was used as headquarters of the Aeroclub of Catalonia and the base for the Spanish Navy\'s Zeppelin fleet. Scheduled commercial service began in 1927 with an Iberia service to Madrid Cuatro Vientos Airport. This was Iberia\'s first route. During the time of the Second Spanish Republic El Prat was one of the bases of LAPE (Líneas Aéreas Postales Españolas).')),
   new Photograph('/photographs/2023-05-17/2023-05-17_013.webp', true),
   new Photograph('/photographs/2023-05-17/2023-05-17_014.webp', false, new Text('Montserrat.', 'The new control tower is a hyperboloid structure')),
  ]);

export default BarcelonaAirport;