import Album from '../core/photographyAlbum';
import Photograph from '../core/photograph';
import Text from '../core/text';

const ConqueringAmerica20 = new Album(
  new Text('ConqueringAmerica20', 'Conquering America 2.0'),
  new Date('2017-09-24'),
  new Photograph('/photographs/2017-09-09_24/2017-09-09_24_018_large.webp', false, new Text('ConqueringAmerica20.', 'United States Capitol')),
  [
    new Photograph('/photographs/2017-09-09_24/2017-09-09_24_001_large.webp', true,
      new Text('ConqueringAmerica20.', 'Oculus / World Trade Center Station\n\nOne of the first decisions that Calatrava had in mind at the time of conceiving the project was the realization of the building at street level, an independent structure along the Wedge of Light Square, by Daniel Libeskind. “Oculus”, the centerpiece of the Transportation Center that presents the new station to the world is a kind of pause in the middle of the dense glass and steel towers that surround it.\n\nThe construction, due to constant delays, lasted 12 years and was finally inaugurated on March 3, 2016, without too many celebrations. The cost of its construction, $ 4 billion, greatly exceeded its original cost, becoming, until the time of its inauguration, the most expensive train station in the world and the third largest transportation center in New York, after Grand Central and Penn Station, both in Midtown Manhattan.')),
    new Photograph('/photographs/2017-09-09_24/2017-09-09_24_002_large.webp', false,
      new Text('ConqueringAmerica20.', 'New York Harbor')),
    new Photograph('/photographs/2017-09-09_24/2017-09-09_24_003_large.webp', true,
      new Text('ConqueringAmerica20.', 'Manhattan Bridge\n\nThe bridge was designed by Leon Moisseiff, built by The Phoenix Bridge Company, and opened to traffic on December 31, 1909. An innovative design, it was the first suspension bridge to employ Josef Melan\'s deflection theory for deck stiffening, resulting in the first use of a lightly-webbed weight-saving Warren truss for its construction. Considered the forerunner of modern suspension bridges, it served as the model for many of the record-breaking spans built in the first half of the twentieth century.')),
    new Photograph('/photographs/2017-09-09_24/2017-09-09_24_004_large.webp', true,
      new Text('ConqueringAmerica20.', 'Cycling in New York City\n\nApproximately eight hundred thousand New Yorkers ride a bike regularly. It is estimated that over 530,000 cycling trips are made each day in New York City.')),
    new Photograph('/photographs/2017-09-09_24/2017-09-09_24_005_large.webp', true,
      new Text('ConqueringAmerica20.', 'Street Art by Tiara Zhane')),
    new Photograph('/photographs/2017-09-09_24/2017-09-09_24_006_large.webp', false,
      new Text('ConqueringAmerica20.', 'Painter in Central Park')),
    new Photograph('/photographs/2017-09-09_24/2017-09-09_24_007_large.webp', true),
    new Photograph('/photographs/2017-09-09_24/2017-09-09_24_008_large.webp'),
    new Photograph('/photographs/2017-09-09_24/2017-09-09_24_009_large.webp', true,
      new Text('ConqueringAmerica20.', '6th Avenue & West 57th Street')),
    new Photograph('/photographs/2017-09-09_24/2017-09-09_24_010_large.webp', true,
      new Text('ConqueringAmerica20.', '6th Avenue & West 57th Street')),
    new Photograph('/photographs/2017-09-09_24/2017-09-09_24_011_large.webp', true,
      new Text('ConqueringAmerica20.', '6th Avenue & West 42nd Street')),
    new Photograph('/photographs/2017-09-09_24/2017-09-09_24_012_large.webp', false,
      new Text('ConqueringAmerica20.', 'Grand Central Terminal\n\nGrand Central Terminal was built by and named for the New York Central Railroad; it also served the New York, New Haven, and Hartford Railroad and, later, successors to the New York Central. Opened in 1913, the terminal was built on the site of two similarly-named predecessor stations, the first of which dates to 1871. Grand Central Terminal served intercity trains until 1991, when Amtrak began routing its trains through nearby Penn Station. The East Side Access project, which will bring Long Island Rail Road service to the new Grand Central Madison station beneath the terminal, is expected to be completed in late 2022.')),
    new Photograph('/photographs/2017-09-09_24/2017-09-09_24_013_large.webp', false,
    new Text('ConqueringAmerica20.', 'On the Streets of New York')),
    new Photograph('/photographs/2017-09-09_24/2017-09-09_24_014_large.webp', true,
      new Text('ConqueringAmerica20.', 'Arlington National Cemetery\n\nArlington National Cemetery is a United States military cemetery in Arlington County, across the Potomac River from Washington, D.C., in whose 259 ha the dead of the nation\'s conflicts have been buried, beginning with the Civil War, as well as reinterred dead from earlier wars. The United States Department of the Army, a component of the United States Department of Defense (DoD), controls the cemetery.')),
    new Photograph('/photographs/2017-09-09_24/2017-09-09_24_015_large.webp', true,
      new Text('ConqueringAmerica20.', 'The national cemetery was established during the Civil War on the grounds of Arlington House, previously the estate of Mary Anna Custis Lee, a great-granddaughter of Martha Washington and wife of Robert E. Lee. The Cemetery, along with Arlington House, Memorial Drive, the Hemicycle, and Arlington Memorial Bridge form the Arlington National Cemetery Historic District, listed on the National Register of Historic Places in April 2014.')),
    new Photograph('/photographs/2017-09-09_24/2017-09-09_24_016_large.webp', true,
      new Text('ConqueringAmerica20.', 'The Cemetery is divided into 70 sections, with some sections in the southeast and western part of the cemetery reserved for future expansion. Section 60, in the southeast part of the cemetery, is the burial ground for military personnel killed in the "war on terror" since 2001. Section 21, also known as the Nurses Section, is the burial site for many nurses, and the location of the Spanish - American War Nurses Memorial and the Nurses Memorial. Another section - Chaplains Hill - includes monuments to Jewish, Protestant, and Roman Catholic military chaplains.')),
    new Photograph('/photographs/2017-09-09_24/2017-09-09_24_017_large.webp', true,
      new Text('ConqueringAmerica20.', 'Lincoln Memorial')),
    new Photograph('/photographs/2017-09-09_24/2017-09-09_24_018_large.webp', false,
      new Text('ConqueringAmerica20.', 'United States Capitol\n\nThe United States Capitol, often called The Capitol or the Capitol Building, is the meeting place of the United States Congress and the seat of the legislative branch of the U.S. federal government. Though no longer at the geographic center of the federal district, the Capitol forms the origin point for the district\'s street-numbering system and the district\'s four quadrants.')),
    new Photograph('/photographs/2017-09-09_24/2017-09-09_24_019_large.webp', true,
      new Text('ConqueringAmerica20.', 'Special Effects Show at Universal Studios Hollywood\n\nUniversal Studios Hollywood is a film studio and theme park in the San Fernando Valley area of Los Angeles County. About 70% of the studio lies within the unincorporated county island known as Universal City while the rest lies within the city limits of Los Angeles. It is one of the oldest and most famous Hollywood film studios still in use. Its official marketing headline is "The Entertainment Capital of LA". It was initially created to offer tours of the real Universal Studios sets and is the first of many full-fledged Universal Studios Theme Parks located across the world.')),
    new Photograph('/photographs/2017-09-09_24/2017-09-09_24_020_large.webp', true,
      new Text('ConqueringAmerica20.', 'The attraction serves as a new version of the park\'s former Special Effects Stages show, which was located in the Lower Lot area and was relocated to the Upper Lot’s Castle Theater to make way for Transformers: The Ride 3D. The attraction takes guests through demonstrations of how movie special effects are created, including Motion capture, Chroma key, and Stop motion techniques.')),
    new Photograph('/photographs/2017-09-09_24/2017-09-09_24_021_large.webp', true,
      new Text('ConqueringAmerica20.', 'Foucault Pendulum / Griffith Observatory\n\nThe gently swaying Foucault Pendulum in the W.M. Keck Foundation Central Rotunda has long been a visitor favorite since the building opened in 1935. One of the largest such devices in the world, the fully restored pendulum is actually an elegant scientific instrument which demonstrates the Earth’s rotation.\n\nThe 240-pound bronze ball, suspended by a cable 40 feet long, swings in a constant direction while the Earth turns beneath it. The pendulum is mounted to a bearing in the rotunda ceiling that does not turn with the building as it rotates with the Earth. A ring magnet at the bearing gives a little tug on each swing of the pendulum to keep the pendulum in motion. As the day passes, the pendulum knocks over pegs set up in the pendulum pit and indicates the progress of rotation.')),
    new Photograph('/photographs/2017-09-09_24/2017-09-09_24_022_large.webp', true,
      new Text('ConqueringAmerica20.', 'Golden Gate Bridge\n\nThe Golden Gate Bridge is a suspension bridge spanning the Golden Gate, the one-mile-wide strait connecting San Francisco Bay and the Pacific Ocean. Being declared one of the Wonders of the Modern World by the American Society of Civil Engineers, the bridge is one of the most internationally recognized symbols of San Francisco and California. It was initially designed by engineer Joseph Strauss in 1917.')),
    new Photograph('/photographs/2017-09-09_24/2017-09-09_24_023_large.webp', false,
      new Text('ConqueringAmerica20.', 'Lombard Street\n\nLombard Street is an east–west street in San Francisco, that is famous for a steep, one-block section with eight hairpin turns. The famous one-block section, claimed to be "the crookedest street in the world", is located along the eastern segment in the Russian Hill neighborhood. It is a major tourist attraction, receiving around two million visitors per year and up to 17,000 per day on busy summer weekends, as of 2015.')),
    new Photograph('/photographs/2017-09-09_24/2017-09-09_24_024_large.webp', false,
      new Text('ConqueringAmerica20.', 'Brighton Beach Train / Brooklyn')),
    new Photograph('/photographs/2017-09-09_24/2017-09-09_24_025_large.webp', false,
      new Text('ConqueringAmerica20.', 'Brooklyn Bridge')),
    new Photograph('/photographs/2017-09-09_24/2017-09-09_24_026_large.webp', false,
      new Text('ConqueringAmerica20.', 'Breakfast at Tiffany\'s / Park Avenue and East 52nd Street, Manhattan\n\nBreakfast at Tiffany\'s is a 1961 American romantic comedy film directed by Blake Edwards, written by George Axelrod, adapted from Truman Capote\'s 1958 novella of the same name, and starring Audrey Hepburn as Holly Golightly, a naïve, eccentric café society girl who falls in love with a struggling writer.')),
    new Photograph('/photographs/2017-09-09_24/2017-09-09_24_027_large.webp', true,
      new Text('ConqueringAmerica20.', 'Flatiron Building is a triangular 22-story steel-framed landmarked building located at 175 Fifth Avenue in the borough of Manhattan, and is considered to be a groundbreaking skyscraper.')),
    new Photograph('/photographs/2017-09-09_24/2017-09-09_24_028_large.webp', true),
    new Photograph('/photographs/2017-09-09_24/2017-09-09_24_029_large.webp', false,
      new Text('ConqueringAmerica20.', 'Brooklyn Bridge - one of the oldest roadway bridges in the United States. Started in 1869 and completed fourteen years later in 1883, it connects the boroughs of Manhattan and Brooklyn, spanning the East River.')),
    new Photograph('/photographs/2017-09-09_24/2017-09-09_24_030_large.webp', true,
      new Text('ConqueringAmerica20.',  'Dumbo\n\nThe area known as Dumbo used to be known as Gairville. The area was originally a ferry landing, characterized by 19th- and early 20th-century industrial and warehouse buildings, Belgian block streets, and its location on the East River by the imposing anchorage of the Manhattan Bridge. The entirety of Dumbo was bought by developer David Walentas and his company Two Trees Management in the late 20th century, and remade into an upscale residential and commercial community—first becoming a haven for art galleries, and currently a center for technology startups.')),
  ]);

export default ConqueringAmerica20;